FROM node:current-alpine3.14

RUN apk add chromium
WORKDIR /app
ENV CHROME_BIN=/usr/bin/chromium-browser

WORKDIR /usr/local/app
COPY package.json /usr/local/app/package.json
RUN npm install

COPY ./ /usr/local/app/
RUN npm test -- --no-watch --browsers=ChromeHeadless
#CMD ["npm","test","--","--no-sandbox","--no-watch","--browsers=ChromeHeadless"]